/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.8.0
 * Thu, 23 Jan 2025 23:46:40 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.type !== 'AmbientLight' && obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable && objName in _pGlob.objCache) {
            objFound = _pGlob.objCache[objName] || null;
        }
    
        if (objFound && objFound.name === objName) {
            return objFound;
        }
    
        if (appInstance.scene) {
            appInstance.scene.traverse(obj => {
                if (!objFound && isObjectWorthProcessing(obj) && (obj.name === objName)) {
                    objFound = obj;
                    if (pGlobAvailable) {
                        _pGlob.objCache[objName] = objFound;
                    }
                }
            });
        }
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    class AudioWebAudio {
        constructor() {
            this.audio = new v3d.Audio(new v3d.AudioListener());
    
            this._muted = false;
            this._volume = 1;
        }
    
        load(url) {
            const scope = this;
    
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.responseType = 'arraybuffer';
    
            xhr.onload = function(e) {
                if (this.status === 200) {
                    // new promise-based syntax is not currently supported in Safari
                    scope.audio.context.decodeAudioData(this.response, function(decodedData) {
                        scope.audio.setBuffer(decodedData);
                    });
                }
            }
    
            xhr.send();
            return this;
        }
    
        play() {
            if (this.audio.buffer === null) return;
            this.audio.play();
        }
    
        pause() {
            this.audio.pause();
        }
    
        stop() {
            if (this.audio.buffer === null || this.audio.source === null) return;
            this.audio.stop();
        }
    
        rewind() {
            if (this.audio.buffer === null || this.audio.source === null) return;
    
            const isPlaying = this.audio.isPlaying;
            this.audio.stop();
            if (isPlaying) {
                this.audio.play();
            }
        }
    
        setPlaybackTime(time) {
            // TODO: not easy with WebAudio
        }
    
        getPlaybackTime() {
            // TODO: not easy with WebAudio
            return 0;
        }
    
        getDuration() {
            return (this.audio.buffer === null) ? 0 : this.audio.buffer.duration;
        }
    
        setPlaybackRate(rate) {
            this.audio.setPlaybackRate(rate);
        }
    
        isPlaying() {
            return this.audio.isPlaying;
        }
    
        setLoop(looped) {
            this.audio.setLoop(looped);
        }
    
        setVolume(volume) {
            this._volume = volume;
            if (!this._muted) {
                this.audio.setVolume(volume);
            }
        }
    
        setMuted(muted) {
            this._muted = muted;
            this.audio.setVolume(muted ? 0 : this._volume);
        }
    
        toPositional() {
            if (!(this.audio instanceof v3d.PositionalAudio)) {
                const posAudio = new v3d.PositionalAudio(this.audio.listener);
                posAudio.fromAudio(this.audio);
                this.audio = posAudio;
            }
            return this.audio;
        }
    }
        
    function getObjectName(obj) {
        // auto-generated from a multi-material object, use parent name instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.name;
        } else {
            return obj.name;
        }
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function initObjectPicking(callback, eventType, mouseDownUseTouchStart=false,
            allowedMouseButtons=null) {
    
        const elem = appInstance.renderer.domElement;
        bindListener(elem, eventType, pickListener);
    
        if (eventType === 'mousedown') {
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, pickListener);
    
        } else if (eventType === 'dblclick') {
    
            let prevTapTime = 0;
    
            function doubleTapCallback(event) {
                const now = new Date().getTime();
                const timesince = now - prevTapTime;
    
                if (timesince < 600 && timesince > 0) {
                    pickListener(event);
                    prevTapTime = 0;
                    return;
                }
    
                prevTapTime = new Date().getTime();
            }
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, doubleTapCallback);
        }
    
        const raycaster = new v3d.Raycaster();
    
        function pickListener(event) {
    
            // to handle unload in loadScene puzzle
            if (!appInstance.getCamera()) {
                return;
            }
    
            event.preventDefault();
    
            let xNorm = 0;
            let yNorm = 0;
            if (event instanceof MouseEvent) {
                if (allowedMouseButtons !== null && allowedMouseButtons.indexOf(event.button) === -1) {
                    return;
                }
                xNorm = event.offsetX / elem.clientWidth;
                yNorm = event.offsetY / elem.clientHeight;
            } else if (event instanceof TouchEvent) {
                const rect = elem.getBoundingClientRect();
                xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
                yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
            }
    
            _pGlob.screenCoords.x = xNorm * 2 - 1;
            _pGlob.screenCoords.y = -yNorm * 2 + 1;
            raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
    
            const objList = [];
            appInstance.scene.traverse(obj => objList.push(obj));
    
            const intersects = raycaster.intersectObjects(objList, false);
            callback(intersects, event);
        }
    }
        
    function isObjectAmongObjects(objNameToCheck, objNames) {
        if (!objNameToCheck) {
            return false;
        }
    
        for (let i = 0; i < objNames.length; i++) {
            if (objNameToCheck === objNames[i]) {
                return true;
            } else {
                // also check children which are auto-generated for multi-material objects
                const obj = getObjectByName(objNames[i]);
                if (obj && obj.type === 'Group') {
                    for (let j = 0; j < obj.children.length; j++) {
                        if (objNameToCheck === obj.children[j].name) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
        
    function getSceneAnimFrameRate(scene) {
        if (scene && 'animFrameRate' in scene.userData) {
            return scene.userData.animFrameRate;
        }
        return 24;
    }
        
    function getSceneByAction(action) {
        const root = action.getRoot();
        let scene = root.type === 'Scene' ? root : null;
        root.traverseAncestors(ancObj => {
            if (ancObj.type === 'Scene') {
                scene = ancObj;
            }
        });
        return scene;
    }

    return {
        getObjectByName, retrieveObjectNames, AudioWebAudio, getObjectName,
        initObjectPicking, isObjectAmongObjects, bindListener, getSceneAnimFrameRate,
        getSceneByAction,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    
    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



var battery, handle, hood, lens;

// outline puzzle
function outline(objSelector, doWhat) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    if (!appInstance.postprocessing || !appInstance.postprocessing.outlinePass)
        return;
    var outlineArray = appInstance.postprocessing.outlinePass.selectedObjects;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        if (doWhat == "ENABLE") {
            if (outlineArray.indexOf(obj) == -1)
                outlineArray.push(obj);
        } else {
            var index = outlineArray.indexOf(obj);
            if (index > -1)
                outlineArray.splice(index, 1);
        }
    }
}

// loadMedia puzzle
function loadMedia_WebAudio(url) {
    if (!v3d.Detector.checkWebAudio()) {
        if (!_pGlob.noWebAudioReported) {
            _pGlob.noWebAudioReported = true;
            console.warn('puzzles: Web Audio API not supported');
        }
        return null;
    }

    var elems = _pGlob.mediaElements;
    if (!(url in elems)) {
        elems[url] = new PzLib.AudioWebAudio().load(url);
    }
    return elems[url];
}

// isSoundPlaying puzzle
function isSoundPlaying(mediaElem) {
    if (!mediaElem)
        return false;
    return mediaElem.isPlaying();
}

// stopSound puzzle
function stopSound(mediaElem) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.stop();
    });
}

// playSound puzzle
function playSound(mediaElem, loop) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.setLoop(loop);
        if (mediaElem.audio)
            mediaElem.audio.context.resume();
        mediaElem.play();
    });
}

// whenHovered puzzle
PzLib.initObjectPicking(function(intersects, event) {

    var prevHovered = _pGlob.hoveredObject;
    var currHovered = '';

    // the event might happen before hover registration
    _pGlob.objHoverInfo = _pGlob.objHoverInfo || [];

    // search for closest hovered object

    var lastIntersectIndex = Infinity;
    _pGlob.objHoverInfo.forEach(function(el) {
        var maxIntersects = el.xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = PzLib.getObjectName(obj);

            if (PzLib.isObjectAmongObjects(objName, PzLib.retrieveObjectNames(el.objSelector)) && i <= lastIntersectIndex) {
                currHovered = objName;
                lastIntersectIndex = i;
            }
        }
    });

    if (prevHovered == currHovered) return;

    // first - all "out" callbacks, then - all "over"
    _pGlob.objHoverInfo.forEach(function(el) {
        if (PzLib.isObjectAmongObjects(prevHovered, PzLib.retrieveObjectNames(el.objSelector))) {
            // ensure the correct value of the hoveredObject block
            _pGlob.hoveredObject = prevHovered;
            el.callbacks[1](event);
        }
    });

    _pGlob.objHoverInfo.forEach(function(el) {
        if (PzLib.isObjectAmongObjects(currHovered, PzLib.retrieveObjectNames(el.objSelector))) {
            // ensure the correct value of the hoveredObject block
            _pGlob.hoveredObject = currHovered;
            el.callbacks[0](event);
        }
    });

    _pGlob.hoveredObject = currHovered;
}, 'mousemove');

// whenHovered puzzle
function registerOnHover(objSelector, xRay, cbOver, cbOut) {

    _pGlob.objHoverInfo = _pGlob.objHoverInfo || [];

    _pGlob.objHoverInfo.push({
        objSelector: objSelector,
        callbacks: [cbOver, cbOut],
        xRay: xRay
    });
}

_pGlob.animMixerCallbacks = [];

var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            PzLib.bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = PzLib.getSceneByAction(action);
                var frameRate = PzLib.getSceneAnimFrameRate(scene);

                action.repetitions = Infinity;

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = PzLib.getSceneByAction(action);
            var frameRate = PzLib.getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            var timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}

// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        callbacks: [cbDo, cbIfMissedDo]
    });

    PzLib.initObjectPicking(function(intersects, event) {

        var isPicked = false;

        var maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = PzLib.getObjectName(obj);
            var objNames = PzLib.retrieveObjectNames(objSelector);

            if (PzLib.isObjectAmongObjects(objName, objNames)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}


registerOnHover('body', false, function() {
  outline('body', 'ENABLE');
  outline('BODY (TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/body.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    playSound(loadMedia_WebAudio('audio/body.mp3'), false);
  }
}, function() {
  outline('body', 'DISABLE');
  outline('BODY (TEXT)', 'DISABLE');
});

registerOnHover('BODY (TEXT)', false, function() {
  outline('body', 'ENABLE');
  outline('BODY (TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/body.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    playSound(loadMedia_WebAudio('audio/body.mp3'), false);
  }
}, function() {
  outline('body', 'DISABLE');
  outline('BODY (TEXT)', 'DISABLE');
});

battery = false;

handle = false;

hood = false;

lens = false;

registerOnHover('BATERAI', false, function() {
  outline('BATERAI', 'ENABLE');
  outline('BATTERY(TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/baterai.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/baterai.mp3'), false);
  }
}, function() {
  outline('BATERAI', 'DISABLE');
  outline('BATTERY(TEXT)', 'DISABLE');
});

registerOnHover('BATTERY(TEXT)', false, function() {
  outline('BATTERY(TEXT)', 'ENABLE');
  outline('BATERAI', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/baterai.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/baterai.mp3'), false);
  }
}, function() {
  outline('BATTERY(TEXT)', 'DISABLE');
  outline('BATERAI', 'DISABLE');
});

registerOnHover('173', false, function() {
  outline('173', 'ENABLE');
  outline('HOOD(TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/hood.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/hood.mp3'), false);
  }
}, function() {
  outline('173', 'DISABLE');
  outline('HOOD(TEXT)', 'DISABLE');
});

registerOnHover('HOOD(TEXT)', false, function() {
  outline('HOOD(TEXT)', 'ENABLE');
  outline('173', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/hood.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/hood.mp3'), false);
  }
}, function() {
  outline('HOOD(TEXT)', 'DISABLE');
  outline('173', 'DISABLE');
});

registerOnHover('LENSA', false, function() {
  outline('LENSA', 'ENABLE');
  outline('LENS (TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/lensa.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/lensa.mp3'), false);
  }
}, function() {
  outline('LENSA', 'DISABLE');
  outline('LENS (TEXT)', 'DISABLE');
});

registerOnHover('LENS (TEXT)', false, function() {
  outline('LENS (TEXT)', 'ENABLE');
  outline('LENSA', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/lensa.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/gagang.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/lensa.mp3'), false);
  }
}, function() {
  outline('LENS (TEXT)', 'DISABLE');
  outline('LENSA', 'DISABLE');
});

registerOnClick('BATERAI', false, false, [0,1,2], function() {
  if (battery == false) {
    battery = true;

    operateAnimation('PLAY', 'BATERAI', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('BATTERY(TEXT)', false, false, [0,1,2], function() {
  if (battery == false) {
    battery = true;

    operateAnimation('PLAY', 'BATERAI', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('HOOD(TEXT)', false, false, [0,1,2], function() {
  if (hood == false && lens == true) {
    hood = true;

    operateAnimation('PLAY', '173', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('173', false, false, [0,1,2], function() {
  if (hood == false && lens == true) {
    hood = true;

    operateAnimation('PLAY', '173', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('LENSA', false, false, [0,1,2], function() {
  if (lens == false) {
    lens = true;

    operateAnimation('PLAY', 'LENSA', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('LENS (TEXT)', false, false, [0,1,2], function() {
  if (lens == false) {
    lens = true;

    operateAnimation('PLAY', 'LENSA', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('PEGANGAN', false, false, [0,1,2], function() {
  if (handle == false) {
    handle = true;

    operateAnimation('PLAY', 'PEGANGAN', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnClick('HANDLE (TEXT)', false, false, [0,1,2], function() {
  if (handle == false) {
    handle = true;

    operateAnimation('PLAY', 'PEGANGAN', null, null, 'LoopOnce', 1,
            function() {}, false);

        }
}, function() {});

registerOnHover('PEGANGAN', false, function() {
  outline('PEGANGAN', 'ENABLE');
  outline('HANDLE (TEXT)', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/gagang.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/gagang.mp3'), false);
  }
}, function() {
  outline('PEGANGAN', 'DISABLE');
  outline('HANDLE (TEXT)', 'DISABLE');
});

registerOnHover('HANDLE (TEXT)', false, function() {
  outline('HANDLE (TEXT)', 'ENABLE');
  outline('PEGANGAN', 'ENABLE');
  if (isSoundPlaying(loadMedia_WebAudio('audio/gagang.mp3')) == false) {
    stopSound(loadMedia_WebAudio('audio/hood.mp3'));
    stopSound(loadMedia_WebAudio('audio/lensa.mp3'));
    stopSound(loadMedia_WebAudio('audio/baterai.mp3'));
    stopSound(loadMedia_WebAudio('audio/body.mp3'));
    playSound(loadMedia_WebAudio('audio/gagang.mp3'), false);
  }
}, function() {
  outline('HANDLE (TEXT)', 'DISABLE');
  outline('PEGANGAN', 'DISABLE');
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
